const request = require("supertest");
const app = require("../server"); 
const Appointment = require("../class-models/Appointment"); 
const transporter = require("../mailer");

jest.mock("../class-models/Appointment"); 
jest.mock("../mailer", () => ({
  sendMail: jest.fn().mockResolvedValue({ messageId: "mock-email-id" }),
}));


describe("GET /get-appointments", () => {
  afterEach(() => {
    jest.clearAllMocks(); 
  });

  test("should return all appointments", async () => {
    
    const mockAppointments = [
      { _id: "1", userName: "John Doe", date: "2025-03-10", time: "10:00 AM", information: "Blessing" },
      { _id: "2", userName: "Jane Smith", date: "2025-03-11", time: "12:00 PM", information: "Healing" },
    ];
    Appointment.find.mockResolvedValue(mockAppointments);

    const response = await request(app).get("/get-appointments");

    expect(response.status).toBe(200);
    expect(response.body).toEqual(mockAppointments);
    expect(Appointment.find).toHaveBeenCalledTimes(1); 
  });

  test("should return an empty array if no appointments exist", async () => {
    
    Appointment.find.mockResolvedValue([]);

    const response = await request(app).get("/get-appointments");

    expect(response.status).toBe(200);
    expect(response.body).toEqual([]);
    expect(Appointment.find).toHaveBeenCalledTimes(1); 
  });

  test("should return 500 if there is a database error", async () => {
    
    Appointment.find.mockRejectedValue(new Error("Database error"));

    const response = await request(app).get("/get-appointments");

    expect(response.status).toBe(500);
    expect(response.text).toContain("Error fetching appointments");
    expect(Appointment.find).toHaveBeenCalledTimes(1); 
  });
});

describe("POST /book-appointment", () => {
  afterEach(() => {
    jest.clearAllMocks(); 
  });

  /*
  test("POST /book-appointment - should create an appointment and send email", async () => {
    const mockAppointment = {
      priestId: "679bdb7d5557d12d5684acc",
      priest: "Batman Iam",
      date: "2025-02-24",
      time: "15:30 PM",
      information: "qwerty",
      userName: "Madan Kumar",
      email: "madankumark14@gmail.com",
    };
  
    Appointment.prototype.save = jest.fn().mockResolvedValue({
      ...mockAppointment,
      _id: "67be0d60b7bbca197b3914c6", // Auto-generated ID from MongoDB
      __v: 0, // Auto-generated by Mongoose
    });
  
    transporter.sendMail.mockResolvedValue({ messageId: "mock-email-id" });
  
    const response = await request(app)
      .post("/book-appointment")
      .send(mockAppointment)
      .expect("Content-Type", /json/) // Ensure JSON response
      .expect(201); // Expect 201 Created status
  
    console.log("Actual Response from API:", response.body); // Debugging output
  
    expect(response.body).toMatchObject({
      priestId: mockAppointment.priestId,
      priest: mockAppointment.priest,
      time: mockAppointment.time,
      information: mockAppointment.information,
      userName: mockAppointment.userName,
      email: mockAppointment.email,
    });
  
    expect(response.body).toHaveProperty("_id");
    expect(Appointment.prototype.save).toHaveBeenCalledTimes(1);
    expect(transporter.sendMail).toHaveBeenCalledTimes(1);
  });
  */
    
  test("POST /book-appointment - should return 500 on server error", async () => {
    Appointment.prototype.save = jest.fn().mockRejectedValue(new Error("Database error"));

    const response = await request(app).post("/book-appointment").send({
      priestId: "123",
      priest: "John Doe",
      date: "2025-03-10",
      time: "10:00 AM",
      information: "Special Pooja",
      userName: "Jane Doe",
      email: "janedoe@example.com",
    });

    expect(response.status).toBe(500);
    expect(response.text).toContain("Error inserting appointment");
    expect(Appointment.prototype.save).toHaveBeenCalledTimes(1);
  });

  test("GET /get-appointments - should retrieve all appointments", async () => {
    const mockAppointments = [
      { _id: "1", userName: "Jane Doe", date: "2025-03-10", time: "10:00 AM" },
      { _id: "2", userName: "John Smith", date: "2025-03-12", time: "11:00 AM" },
    ];

    Appointment.find.mockResolvedValue(mockAppointments);

    const response = await request(app).get("/get-appointments");

    expect(response.status).toBe(200);
    expect(response.body.length).toBe(2);
    expect(response.body).toEqual(mockAppointments);
    expect(Appointment.find).toHaveBeenCalledTimes(1);
  });

  /*
  test("DELETE /delete-appointment/:id - should delete an appointment and send email", async () => {
    const mockAppointment = {
      _id: "660f1d2a8f1b2a5b6c123456",
      priest: "John Doe",
      date: "2025-03-10",
      time: "10:00 AM",
      information: "Special Pooja",
      userName: "Jane Doe",
      email: "janedoe@example.com",
    };

    Appointment.findById.mockResolvedValue(mockAppointment);
    Appointment.findByIdAndDelete.mockResolvedValue(mockAppointment);
    transporter.sendMail.mockResolvedValue({ messageId: "mock-email-id" });

    const response = await request(app).delete(`/delete-appointment/${mockAppointment._id}`);

    expect(response.status).toBe(200);
    expect(response.text).toContain("deleted successfully");
    expect(Appointment.findById).toHaveBeenCalledTimes(1);
    expect(Appointment.findByIdAndDelete).toHaveBeenCalledTimes(1);
    expect(transporter.sendMail).toHaveBeenCalledTimes(1);
  });
  */

  test("DELETE /delete-appointment/:id - should return 404 if appointment not found", async () => {
    Appointment.findById.mockResolvedValue(null);

    const response = await request(app).delete("/delete-appointment/invalid-id");

    expect(response.status).toBe(404);
    expect(response.text).toContain("Appointment not found");
    expect(Appointment.findById).toHaveBeenCalledTimes(1);
    expect(Appointment.findByIdAndDelete).not.toHaveBeenCalled();
  });

  test("PATCH /update-appointment/:id - should update appointment status", async () => {
    const updatedAppointment = { _id: "1", status: "Confirmed" };

    Appointment.findByIdAndUpdate.mockResolvedValue(updatedAppointment);

    const response = await request(app)
      .patch("/update-appointment/1")
      .send({ status: "Confirmed" });

    expect(response.status).toBe(200);
    expect(response.body).toMatchObject(updatedAppointment);
    expect(Appointment.findByIdAndUpdate).toHaveBeenCalledTimes(1);
  });

  test("PATCH /update-appointment/:id - should return 404 if appointment not found", async () => {
    Appointment.findByIdAndUpdate.mockResolvedValue(null);

    const response = await request(app)
      .patch("/update-appointment/invalid-id")
      .send({ status: "Confirmed" });

    expect(response.status).toBe(404);
    expect(response.text).toContain("Appointment not found");
    expect(Appointment.findByIdAndUpdate).toHaveBeenCalledTimes(1);
  });
});
